<?php

function galaxy_status_perform_checks(array $emails)
{
    $instances = db_select('tripal_galaxy', 'T')->fields('T')->execute()->fetchAll();
    foreach ($instances as $instance) {
        $galaxy = tripal_galaxy_get_connection($instance->galaxy_id);
        $galaxy->instance = $instance;

        $not_working = [];
        if ($galaxy) {
            $version = $galaxy->getVersion();
            if (! $version || ! isset($version['version_major'])) {
                $not_working[] = $galaxy;
            }
        }
    }

    if (! empty($not_working)) {
        $message = "The following Galaxy instances are not working:\n";
        foreach ($not_working as $item) {
            $message .= "{$item->instance->servername}: {$item->instance->url}\n";
        }

        (new MailCLIMessage())->from(variable_get('site_mail', ''))
            ->subject('[WARNING] Galaxy Down')
            ->to($emails)
            ->message($message)
            ->send();
    }
}
